name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Cập nhật phiên bản PHP tương ứng

      - name: Install PHP_CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP_CodeSniffer
        run: |
          ~/.composer/vendor/bin/phpcs --standard=PSR12 .

