name: CI for WordPress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # hoặc phiên bản PHP mà dự án của bạn sử dụng

    - name: Check PHP version
      run: php -v

    - name: Install Composer
      run: |
        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
            >&2 echo 'ERROR: Invalid installer signature'
            rm composer-setup.php
            exit 1
        fi
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        rm composer-setup.php
        composer self-update --2.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
        composer install

    - name: Start Docker Compose
      run: |
        docker-compose -f path/to/your/docker-compose.yml up -d  # Cập nhật đường dẫn nếu cần
        sleep 15  # Chờ cho Docker container khởi động

    - name: Run tests
      run: |
        # Chạy các bài kiểm tra của bạn ở đây, ví dụ:
        phpunit
