name: PHP Lint WordPress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install WordPress
        run: |
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          rm -rf wordpress latest.tar.gz

      - name: Install PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/phpunit

      - name: Run PHP linting
        run: find . -type f -name "*.php" -exec php -l {} \;
