name: CI

on:
  push:
    branches:
      - master  # Thay 'main' bằng tên nhánh chính của bạn
  pull_request:
    branches:
      - master  # Thay 'main' bằng tên nhánh chính của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Thay '7.4' bằng phiên bản PHP bạn đang sử dụng

      - name: Set up WordPress
        run: |
          # Download and set up WordPress (replace with your WordPress setup script)
          wget -q -O wordpress.zip https://wordpress.org/latest.zip
          unzip -q wordpress.zip
          mv wordpress/* .
          rm -rf wordpress wordpress.zip

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit ^9

      - name: Run PHP unit tests
        run: vendor/bin/phpunit

      # Add more steps as needed, such as linting, integration tests, deployment, etc.
