name: CI/CD Pipeline for WordPress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_php:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Chọn phiên bản PHP phù hợp

      - name: Install PHP dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer install

      - name: Run PHP CodeSniffer
        run: |
          vendor/bin/phpcs --standard=WordPress .
