name: PHP Project CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Replace with steps specific to your project
    - name: Run PHP tests
      run: vendor/bin/phpunit
