name: PHP CI

on:
  push:
    branches:
      - master  # Thay thế bằng tên nhánh mặc định của bạn
  pull_request:
    branches:
      - master  # Thay thế bằng tên nhánh mặc định của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Thay thế bằng phiên bản PHP của bạn

      - name: Install Composer dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text --colors=never

