name: CI for WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # hoặc phiên bản PHP mà dự án của bạn sử dụng

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
        docker-compose up -d
        sleep 15  # Chờ cho Docker container khởi động

    - name: Run tests
      run: |
        # Chạy các bài kiểm tra của bạn ở đây, ví dụ:
        phpunit
